apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "local-llm-api.fullname" . }}
  labels:
    {{- include "local-llm-api.labels" . | nindent 4 }}

spec:
  strategy:
    type: Recreate

  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "local-llm-api.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "local-llm-api.selectorLabels" . | nindent 8 }}

    spec:
      containers:
        - name: ai-devops-rag

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

          volumeMounts:
            - name: vector-db
              mountPath: /app/vector_db

          env:
            - name: AI_PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "local-llm-api.fullname" . }}-config
                  key: AI_PROVIDER

            - name: OPENAI_LLM_MODEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "local-llm-api.fullname" . }}-config
                  key: OPENAI_LLM_MODEL

            - name: OPENAI_EMBED_MODEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "local-llm-api.fullname" . }}-config
                  key: OPENAI_EMBED_MODEL

            - name: OLLAMA_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "local-llm-api.fullname" . }}-config
                  key: OLLAMA_BASE_URL

            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key
                  key: OPENAI_API_KEY

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: 8000
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}

          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: 8000
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}

      volumes:
        - name: vector-db
          persistentVolumeClaim:
            claimName: {{ include "local-llm-api.fullname" . }}-vector-db